name: Test package

description: Test one of the packages in this monorepo.

inputs:
  package_name:
    description: The name of the tested package
    required: true

runs:
  using: composite
  steps:
    - name: Install Playwright
      shell: bash
      run: |
        if [[ ${{ inputs.package_name }} == "scratch-render" ]]; then
          npx playwright install --with-deps chromium
        fi
    - name: Test
      working-directory: ./packages/${{ inputs.package_name }}
      shell: bash
      env:
        TAP_REPORTER: "junit"
        TAP_REPORTER_FILE: "test-results/junit.xml"
      run: |
        mkdir -p test-results
        npm run test
    - name: Publish test reports
      if: ${{ !cancelled() }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: "./packages/${{ inputs.package_name }}/test-results/**/*"
        check_name: "Test report for ${{ inputs.package_name }}"
        test_file_prefix: "+packages/${{ inputs.package_name }}/"
    - name: Store Test Results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ inputs.package_name }}-test-output
        path: ./packages/${{ inputs.package_name }}/test-results/*
